#pragma once

#define STM32F405xx 1
#define STM32F4 1
#define STM32 1

#define USE_FULL_ASSERT 1
#define HAL_MODULE_ENABLED 1
#define HAL_ADC_MODULE_ENABLED 1
#define HAL_DMA_MODULE_ENABLED 1
#define HAL_FLASH_MODULE_ENABLED 1
#define HAL_GPIO_MODULE_ENABLED 1
#define HAL_IWDG_MODULE_ENABLED 1
#define HAL_PWR_MODULE_ENABLED 1
#define HAL_RCC_MODULE_ENABLED 1
#define HAL_RTC_MODULE_ENABLED 1
#define HAL_SD_MODULE_ENABLED 1
#define HAL_SPI_MODULE_ENABLED 1
#define HAL_TIM_MODULE_ENABLED 1
#define HAL_UART_MODULE_ENABLED 1
#define HAL_WWDG_MODULE_ENABLED 1
#define HAL_CORTEX_MODULE_ENABLED 1

