dofile("../scripts/percent_line.lua")
dofile("../scripts/play_time.lua")
dofile("../scripts/play_bar.lua")
dofile("../scripts/shift_string.lua")
dofile("../scripts/file_icon.lua")
dofile("../scripts/scroll.lua")
dofile("../scripts/fileviewer.lua")
-- dofile("../scripts/play_status.lua")
dofile("../scripts/start.lua")
