@startuml

/' 
	Для полного отображение следует запускать plantuml так:
	java -DPLANTUML_LIMIT_SIZE=16000 -jar plantuml.jar
'/

package Level_0 {

!include %dirpath()/submodule/module_mc_hardware_interfaces/adc_one_channel.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/adc_multi_channel.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/dac.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/i2c.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/pin.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/pin_multifunc.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/pin_multifunc_it.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/port_8bit.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/port_global.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/pwr.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/rcc.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/spi_master_8bit.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/timer_comp_one_channel.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/tim_cnt.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/tim_int.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/tim_pwm_one_ch.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/uart.h
!include %dirpath()/submodule/module_mc_hardware_interfaces/wdt.h

!include %dirpath()/submodule/module_implementation_for_stm32/inc/adc_one_channel.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/dac.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/pin.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/pin_multifunc.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/pin_multifunc_it.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/port_global.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/pwr.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/rcc.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/spi_master_8bit.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/timer_comp_one_channel.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/tim_cnt.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/tim_int.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/tim_pwm_one_ch.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/uart.h
!include %dirpath()/submodule/module_implementation_for_stm32/inc/wdt.h

mc_interfaces.AdcOneChannel				.[hidden]right.>			mc_interfaces.AdcMultiChannel
mc_interfaces.AdcMultiChannel			.[hidden]right.>			mc_interfaces.Dac
mc_interfaces.Dac						.[hidden]right.>			mc_interfaces.I2cMaster
mc_interfaces.I2cMaster					.[hidden]right.>			mc_interfaces.Pin
mc_interfaces.Pin						.[hidden]right.>			mc_interfaces.PinMultifunc
mc_interfaces.PinMultifunc				.[hidden]right.>			mc_interfaces.PinMultifuncIt
mc_interfaces.PinMultifuncIt				.[hidden]right.>			mc_interfaces.Port8bit
mc_interfaces.Port8bit					.[hidden]right.>			mc_interfaces.PortGlobal
mc_interfaces.PortGlobal					.[hidden]right.>			mc_interfaces.Pwr
mc_interfaces.Pwr						.[hidden]right.>			mc_interfaces.Rcc
mc_interfaces.Rcc						.[hidden]right.>			mc_interfaces.SpiMaster8Bit
mc_interfaces.SpiMaster8Bit				.[hidden]right.>			mc_interfaces.TimCompOneChannel
mc_interfaces.TimCompOneChannel			.[hidden]right.>			mc_interfaces.TimCounter
mc_interfaces.TimCounter					.[hidden]right.>			mc_interfaces.TimInterrupt
mc_interfaces.TimInterrupt				.[hidden]right.>			mc_interfaces.TimPwmOneChannel
mc_interfaces.TimPwmOneChannel			.[hidden]right.>			mc_interfaces.Uart
mc_interfaces.Uart						.[hidden]right.>			mc_interfaces.Wdt

mc.AdcOneChannel				.[hidden]right.>			mc.Dac
mc.Dac							.[hidden]right.>			mc.Pin
mc.Pin							.[hidden]right.>			mc.PinMultifunc
mc.PinMultifunc					.[hidden]right.>			mc.PinMultifuncIt
mc.PinMultifuncIt				.[hidden]right.>			mc.PortGlobal
mc.PortGlobal					.[hidden]right.>			mc.Pwr
mc.Pwr							.[hidden]right.>			mc.Rcc
mc.Rcc							.[hidden]right.>			mc.SpiMaster8Bit
mc.SpiMaster8Bit				.[hidden]right.>			mc.TimCompOneChannel
mc.TimCompOneChannel			.[hidden]right.>			mc.TimCounter
mc.TimCounter					.[hidden]right.>			mc.TimInterrupt
mc.TimInterrupt					.[hidden]right.>			mc.TimPwmOneChannel
mc.TimPwmOneChannel				.[hidden]right.>			mc.Uart

mc -[hidden]down-|> mc_interfaces

}

!include %dirpath()/submodule/module_shift_register/shift_register_8bit_port/inc/shift_register_8bit_port.h
!include %dirpath()/submodule/module_shift_register/shift_register_base/inc/shift_register_base.h
!include %dirpath()/submodule/module_shift_register/shift_register_pin/inc/shift_register_pin.h

!include %dirpath()/submodule/module_lcd_driver/lcd_interface.h
!include %dirpath()/submodule/module_lcd_driver/st7565/inc/mono_lcd_lib_st7565.h
!include %dirpath()/submodule/module_digital_potentiometer/ad5204/inc/module_digital_potentiometer_ad5204.h

/'
ShiftRegister			-[hidden]right-|>			MonoLcd
MonoLcd					-[hidden]right-|>			DigitalPotentiometer

mc_interfaces 	-[hidden]down-|>			ShiftRegister
mc_interfaces 	-[hidden]down-|>			MonoLcd
mc_interfaces 	-[hidden]down-|>			DigitalPotentiometer
'/


@enduml