@startuml

package Level_0 {

!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_adc_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_adc_multi_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_dac.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_i2c.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_pin.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_pin_multifunc.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_pin_multifunc_it.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_port_8bit.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_port_global.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_pwr.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_rcc.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_spi_master_8bit.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_timer_comp_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_timer_counter.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_timer_interrupt.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_timer_pwm_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_uart.h
!include %dirpath%/submodule/module_mc_hardware_interfaces/mc_hardware_interfaces_wdt.h

!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_adc_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_dac.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_pin.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_pin_multifunc.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_pin_multifunc_it.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_port_global.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_pwr.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_rcc.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_spi_master_8bit.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_timer_comp_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_timer_counter.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_timer_interrupt.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_timer_pwm_one_channel.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_uart.h
!include %dirpath%/submodule/module_mc_hardware_interfaces_implementation_for_stm32/inc/mc_hardware_interfaces_implementation_for_stm32_wdt.h

McHardwareInterfaces.AdcOneChannel				.[hidden]right.>			McHardwareInterfaces.AdcMultiChannel
McHardwareInterfaces.AdcMultiChannel			.[hidden]right.>			McHardwareInterfaces.Dac
McHardwareInterfaces.Dac						.[hidden]right.>			McHardwareInterfaces.I2cMaster
McHardwareInterfaces.I2cMaster					.[hidden]right.>			McHardwareInterfaces.Pin
McHardwareInterfaces.Pin						.[hidden]right.>			McHardwareInterfaces.PinMultifunc
McHardwareInterfaces.PinMultifunc				.[hidden]right.>			McHardwareInterfaces.PinMultifuncIt
McHardwareInterfaces.PinMultifuncIt				.[hidden]right.>			McHardwareInterfaces.Port8bit
McHardwareInterfaces.Port8bit					.[hidden]right.>			McHardwareInterfaces.PortGlobal
McHardwareInterfaces.PortGlobal					.[hidden]right.>			McHardwareInterfaces.Pwr
McHardwareInterfaces.Pwr						.[hidden]right.>			McHardwareInterfaces.Rcc
McHardwareInterfaces.Rcc						.[hidden]right.>			McHardwareInterfaces.SpiMaster8Bit
McHardwareInterfaces.SpiMaster8Bit				.[hidden]right.>			McHardwareInterfaces.TimCompOneChannel
McHardwareInterfaces.TimCompOneChannel			.[hidden]right.>			McHardwareInterfaces.TimCounter
McHardwareInterfaces.TimCounter					.[hidden]right.>			McHardwareInterfaces.TimInterrupt
McHardwareInterfaces.TimInterrupt				.[hidden]right.>			McHardwareInterfaces.TimPwmOneChannel
McHardwareInterfaces.TimPwmOneChannel			.[hidden]right.>			McHardwareInterfaces.Uart
McHardwareInterfaces.Uart						.[hidden]right.>			McHardwareInterfaces.Wdt

McHardwareInterfacesImplementation.AdcOneChannel				.[hidden]right.>			McHardwareInterfacesImplementation.Dac
McHardwareInterfacesImplementation.Dac							.[hidden]right.>			McHardwareInterfacesImplementation.Pin
McHardwareInterfacesImplementation.Pin							.[hidden]right.>			McHardwareInterfacesImplementation.PinMultifunc
McHardwareInterfacesImplementation.PinMultifunc					.[hidden]right.>			McHardwareInterfacesImplementation.PinMultifuncIt
McHardwareInterfacesImplementation.PinMultifuncIt				.[hidden]right.>			McHardwareInterfacesImplementation.PortGlobal
McHardwareInterfacesImplementation.PortGlobal					.[hidden]right.>			McHardwareInterfacesImplementation.Pwr
McHardwareInterfacesImplementation.Pwr							.[hidden]right.>			McHardwareInterfacesImplementation.Rcc
McHardwareInterfacesImplementation.Rcc							.[hidden]right.>			McHardwareInterfacesImplementation.SpiMaster8Bit
McHardwareInterfacesImplementation.SpiMaster8Bit				.[hidden]right.>			McHardwareInterfacesImplementation.TimCompOneChannel
McHardwareInterfacesImplementation.TimCompOneChannel			.[hidden]right.>			McHardwareInterfacesImplementation.TimCounter
McHardwareInterfacesImplementation.TimCounter					.[hidden]right.>			McHardwareInterfacesImplementation.TimInterrupt
McHardwareInterfacesImplementation.TimInterrupt					.[hidden]right.>			McHardwareInterfacesImplementation.TimPwmOneChannel
McHardwareInterfacesImplementation.TimPwmOneChannel				.[hidden]right.>			McHardwareInterfacesImplementation.Uart

McHardwareInterfacesImplementation -[hidden]down-|> McHardwareInterfaces

}


!include %dirpath%/submodule/module_shift_register/shift_register.h
!include %dirpath%/submodule/module_shift_register/shift_register_pin.h
!include %dirpath%/submodule/module_shift_register/shift_register_8bit_port.h

!include %dirpath%/submodule/module_lcd_driver/lcd_interface.h
!include %dirpath%/submodule/module_lcd_driver/st7565/mono_lcd_lib_st7565.h
!include %dirpath%/submodule/module_digital_potentiometer/ad5204/module_digital_potentiometer_ad5204.h

/'
ShiftRegister			-[hidden]right-|>			MonoLcd
MonoLcd					-[hidden]right-|>			DigitalPotentiometer

McHardwareInterfaces 	-[hidden]down-|>			ShiftRegister
McHardwareInterfaces 	-[hidden]down-|>			MonoLcd
McHardwareInterfaces 	-[hidden]down-|>			DigitalPotentiometer
'/


@enduml